version: 2.1

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  test-linux:
    docker:
      - image: sudachen/go1144-ci

    steps:
      - checkout
      - run: make build
      - run: make run-linux-tests
      - run: make build-windows-tests
      #- run: make build-osx-tests
      - persist_to_workspace:
          root: .
          paths:
            - .data

  test-windows:
    executor: win/default

    steps:
      - attach_workspace:
          at: .\ws
      - run:
          command: dir /s
          shell: cmd.exe
      - run:
          command: cd .\ws\.data\tests && for %i in (*.exe) do %i -test.v=true -test.coverprofile=%i.out
          shell: cmd.exe
      - persist_to_workspace:
          root: C:\Users\circleci\project\ws
          paths:
            - .data

  test-osx:
    macos:
      xcode: 11.3.0

    steps:
      - attach_workspace:
          at: ./ws
      - run: cd ./ws/.data/tests && for i in ./*.osx; do $i -test.v=true -test.coverprofile=$i.out; done
      - persist_to_workspace:
          root: ./ws
          paths:
            - .data

  test-cover:
    docker:
      - image: alpine:3.7

    environment:
      CC_TEST_REPORTER_ID: 6faa816b8783373b065bcab1cee0278dfd9f5de083e2eb36bb7d2f13e2fc0098

    steps:
      - checkout
      - attach_workspace:
          at: ./ws
      - run: ls -s ./ws/.data .
      - run: make collect-tests
      - run: apk add curl make
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter &
             chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter after-build -t gocov
      - run: make check-fail

workflows:
  version: 2
  test-workflow:
    jobs:
      - test-linux
      - test-windows:
          requires:
            - test-linux
      #- test-osx:
      #    requires:
      #      - test-windows
      - test-cover:
          requires:
            - test-windows


